/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ot2t_bridge_Bridge */

#ifndef _Included_com_ot2t_bridge_Bridge
#define _Included_com_ot2t_bridge_Bridge
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ot2t_bridge_Bridge
 * Method:    initializeBridge
 * Signature: (V)I
 */
JNIEXPORT jint JNICALL Java_com_ot2t_bridge_Bridge_initializeBridge
  (JNIEnv *, jobject);

/*
 * Class:     com_ot2t_bridge_Bridge
 * Method:    shutdownBridge
 * Signature: (V)V
 */
JNIEXPORT void JNICALL Java_com_ot2t_bridge_Bridge_shutdownBridge
  (JNIEnv *, jobject);

/*
 * Class:     com_ot2t_bridge_Bridge
 * Method:    addDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ot2t_bridge_Bridge_addDevice
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
